version: "3"

services:
  web:
    image: ghcr.io/jeremy-virgo/opensis-classic-docker:master
    container_name: opensis
    ports:
      - "8001:80"
    networks:
      - opensis-network
    depends_on:
      - db
  db:
    image: mysql
    container_name: opensis-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./opensis-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opensis # 'opensis' is mysql password
    networks:
      - opensis-network
    command: --sql_mode=""

networks:
  opensis-network:
