version: "3"

services:
  web:
    build: ghcr.io/jeremy-virgo/opensis-classic-docker:master
    ports:
      - "8001:80"
    networks:
      - opensis-network
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./opensis-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opensis # 'opensis' is mysql password
    networks:
      - opensis-network
    command: --sql_mode=""

networks:
  opensis-network:
